version: '3'

volumes:
  db-data:
    external: false

services:
  web:
    image: doteka/dna-api
    build:
      context: .
    depends_on:
      - db
    ports:
      - 80:5000
    environment:
      DB_URI: postgresql://postgres:topsecure@db:5432/dna-api
      TEST_DB_URI: postgresql://postgres:topsecure@db:5432/test-dna-api
      PORT: 5000
    volumes:
      - .:/app
    command: npm run watch

  db:
    image: postgres:11-alpine
    volumes:
      - db-data:/var/lib/postgresql/db-data
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: dna-api
      POSTGRES_PASSWORD: topsecure
